
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import TanStackProvider from "@/components/Providers/TanStackProvider";

const inter = Roboto({ weight : "500",subsets : ["cyrillic-ext"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackProvider>
           <NavBar/>
           {children}
        </TanStackProvider>
       </body>
    </html>
  );
}
